/* The puzzle bank. Add new puzzles here, the daily rotation handles the rest.
   Each puzzle: category, answer (display), accept (normalized match list), 5 clues vague to obvious. */

export const LAUNCH_DATE = new Date(2026, 5, 12); // June 12, 2026 = Puzzle #1

export const PUZZLES = [
  { category: "Movie", answer: "Titanic", accept: ["titanic"], clues: [
    "This 1997 film held the all time box office record for over a decade.",
    "Its director later broke his own record twice with blue aliens and their sequel.",
    "It won 11 Academy Awards, tying the all time record.",
    "Fans still argue whether two people could fit on that floating door.",
    "Leonardo DiCaprio is the king of the world on a doomed ship." ]},
  { category: "Music", answer: "Taylor Swift", accept: ["taylor swift", "tswift", "taylor alison swift"], clues: [
    "This artist started in country music as a teenager before conquering pop.",
    "Fans decode hidden easter eggs in everything this artist releases.",
    "Re recorded earlier albums and stamped them as their own versions.",
    "The Eras Tour became the highest grossing concert tour in history.",
    "Dating a Chiefs tight end made this artist an NFL broadcast fixture." ]},
  { category: "TV Show", answer: "Stranger Things", accept: ["stranger things"], clues: [
    "Set in a fictional small Indiana town in the 1980s.",
    "Single handedly sent a 1985 Kate Bush song back up the charts.",
    "A girl with a shaved head and a nosebleed has powerful abilities.",
    "Kids battle creatures from a dark dimension called the Upside Down.",
    "Eleven loves Eggo waffles." ]},
  { category: "Celebrity", answer: "Dwayne Johnson", accept: ["dwayne johnson", "the rock", "rock", "dwayne the rock johnson"], clues: [
    "Played college football at the University of Miami.",
    "Was a champion in a very different kind of ring before Hollywood.",
    "Famous for one raised eyebrow and asking if you can smell what's cooking.",
    "Now one of the highest paid actors alive, starring in Jumanji and Moana.",
    "His wrestling name is a geological feature." ]},
  { category: "Movie", answer: "The Matrix", accept: ["matrix", "the matrix"], clues: [
    "This 1999 film made trench coats and tiny sunglasses a uniform.",
    "Its slow motion camera trick was named bullet time.",
    "The hero's name is an anagram of One.",
    "You must choose between a red pill and a blue pill.",
    "Keanu Reeves dodges bullets as Neo." ]},
  { category: "Music", answer: "Beyoncé", accept: ["beyonce", "beyonce knowles", "queen bey", "queen b"], clues: [
    "Got their start in a Houston girl group in the late 90s.",
    "Holds the record for the most Grammy wins of any artist.",
    "Dropped a surprise self titled visual album with zero promotion.",
    "Went country with an album called Cowboy Carter.",
    "The BeyHive worships her and her alter ego Sasha Fierce." ]},
  { category: "TV Show", answer: "The Office", accept: ["the office", "office", "the office us"], clues: [
    "A documentary crew films a mid sized paper company for nine seasons.",
    "Set in Scranton, Pennsylvania.",
    "Features a teapot gift, a fire drill gone wrong, and Pretzel Day.",
    "Jim and Pam's romance kept viewers hooked for years.",
    "Michael Scott is the World's Best Boss, per his own mug." ]},
  { category: "Celebrity", answer: "Oprah Winfrey", accept: ["oprah winfrey", "oprah"], clues: [
    "Rose from poverty in Mississippi to become a billionaire media mogul.",
    "Ran the highest rated daytime talk show in TV history for 25 years.",
    "Her book club picks instantly become bestsellers.",
    "Famous for giving an entire studio audience free cars.",
    "You get a car! You get a car! Everybody gets a car!" ]},
  { category: "Movie", answer: "Jurassic Park", accept: ["jurassic park"], clues: [
    "This 1993 blockbuster was based on a Michael Crichton novel.",
    "Its effects were so groundbreaking they changed filmmaking forever.",
    "Life, uh, finds a way in this movie.",
    "A glass of water ripples as something enormous approaches.",
    "Spielberg's theme park of cloned dinosaurs goes very wrong." ]},
  { category: "Music", answer: "Michael Jackson", accept: ["michael jackson", "mj", "michael joseph jackson"], clues: [
    "Began performing with four brothers as a child in Gary, Indiana.",
    "Owns the best selling album of all time, released in 1982.",
    "Famous for a single sparkly glove and a gravity defying lean.",
    "Debuted the moonwalk on live television in 1983.",
    "Known worldwide as the King of Pop." ]},
  { category: "TV Show", answer: "Friends", accept: ["friends"], clues: [
    "This sitcom's Manhattan apartment would cost a fortune in real rent.",
    "Its theme song promises to be there for you.",
    "A paleontologist, a chef, and a masseuse are among the main six.",
    "Catchphrases include How you doin and WE WERE ON A BREAK.",
    "Ross, Rachel, Monica, Chandler, Joey, and Phoebe hang at Central Perk." ]},
  { category: "Celebrity", answer: "Keanu Reeves", accept: ["keanu reeves", "keanu"], clues: [
    "Famous for being one of the nicest people in Hollywood.",
    "A photo of this person eating a sandwich alone became the Sad meme.",
    "Reportedly gave away big chunks of movie profits to film crews.",
    "Starred in Speed, Point Break, and a saga about a stolen puppy's revenge.",
    "He is breathtaking, and he knows kung fu." ]},
  { category: "Movie", answer: "Star Wars", accept: ["star wars", "star wars a new hope", "a new hope", "star wars episode 4", "star wars episode iv"], clues: [
    "This 1977 film opens with text crawling into deep space.",
    "Its composer's brass heavy theme is instantly recognizable.",
    "A farm boy, a smuggler, and a princess take on an empire.",
    "May the Force be with you.",
    "Luke Skywalker blows up the Death Star." ]},
  { category: "Music", answer: "Elvis Presley", accept: ["elvis presley", "elvis"], clues: [
    "Bought a Memphis mansion called Graceland.",
    "His swiveling hips scandalized 1950s television.",
    "Served in the US Army at the height of his fame.",
    "Famous for jumpsuits, sideburns, and Las Vegas residencies.",
    "Known simply as the King of Rock and Roll." ]},
  { category: "TV Show", answer: "Breaking Bad", accept: ["breaking bad"], clues: [
    "Turned an RV in the New Mexico desert into an icon.",
    "Its lawyer spinoff was almost as acclaimed as the original.",
    "The main character adopts the alias Heisenberg.",
    "A mild chemistry teacher becomes a kingpin after a cancer diagnosis.",
    "Walter White is the one who knocks." ]},
  { category: "Celebrity", answer: "Tom Cruise", accept: ["tom cruise"], clues: [
    "Famous for sprinting at full speed in nearly every film.",
    "Insists on doing his own increasingly insane stunts.",
    "Slid across a floor in socks and sunglasses in a 1983 breakout role.",
    "Jumped on Oprah's couch in one of TV's most replayed moments.",
    "Maverick himself, star of Top Gun and Mission Impossible." ]},
  { category: "Movie", answer: "Back to the Future", accept: ["back to the future", "bttf"], clues: [
    "This 1985 film made a commercial flop of a car legendary.",
    "Its hero must make sure his own parents fall in love.",
    "Where we're going, we don't need roads.",
    "The time machine needs 1.21 gigawatts and 88 miles per hour.",
    "Marty McFly and Doc Brown ride a DeLorean through time." ]},
  { category: "Music", answer: "Queen", accept: ["queen"], clues: [
    "This band's logo was designed by its lead singer using zodiac signs.",
    "Their 1985 Live Aid set is called the greatest live performance ever.",
    "A biopic about their frontman won four Oscars.",
    "Stadiums still stomp and clap to one of their anthems.",
    "Freddie Mercury asks if this is the real life or just fantasy." ]},
  { category: "TV Show", answer: "Game of Thrones", accept: ["game of thrones", "got"], clues: [
    "Based on a book series the author still hasn't finished.",
    "Its weddings are events you do not want an invitation to.",
    "Winter is coming.",
    "Dragons, direwolves, and a very pointy chair everyone fights over.",
    "Jon Snow knows nothing, according to Ygritte." ]},
  { category: "Celebrity", answer: "Serena Williams", accept: ["serena williams", "serena"], clues: [
    "Grew up practicing on public courts in Compton, California.",
    "Won a Grand Slam title while pregnant.",
    "Owns 23 major singles titles, the most of the Open Era.",
    "Her older sister was also her greatest rival.",
    "Arguably the greatest tennis player of all time." ]},
  { category: "Movie", answer: "Frozen", accept: ["frozen"], clues: [
    "This 2013 animated film is loosely based on a Hans Christian Andersen tale.",
    "Parents could not escape its soundtrack for years.",
    "A talking snowman dreams about summer.",
    "Two royal sisters, one with dangerous ice powers.",
    "Elsa belts Let It Go." ]},
  { category: "Music", answer: "Drake", accept: ["drake", "aubrey graham", "aubrey drake graham"], clues: [
    "Started out as a wheelchair bound character on a Canadian teen drama.",
    "Reps Toronto so hard the city is nicknamed The Six.",
    "Holds records for the most charted songs in Billboard history.",
    "His dance moves in the Hotline Bling video became instant memes.",
    "Started from the bottom, now he's here." ]},
  { category: "TV Show", answer: "The Simpsons", accept: ["the simpsons", "simpsons"], clues: [
    "The longest running scripted primetime show in American history.",
    "Famous for eerily predicting real world events decades early.",
    "Set in a town of Springfield in a state never revealed.",
    "A nuclear safety inspector who loves donuts and Duff beer.",
    "Homer says D'oh, Bart says Eat my shorts." ]},
  { category: "Celebrity", answer: "Will Smith", accept: ["will smith"], clues: [
    "Started as a Grammy winning rapper before becoming a movie star.",
    "Played a boxing legend and a tennis dad in Oscar nominated roles.",
    "A 90s sitcom had him move from Philadelphia to a rich relative's mansion.",
    "An onstage slap at the 2022 Oscars dominated headlines.",
    "The Fresh Prince of Bel Air himself." ]},
  { category: "Movie", answer: "The Lion King", accept: ["the lion king", "lion king"], clues: [
    "This 1994 animated film borrows its plot from Hamlet.",
    "Elton John wrote its love ballad.",
    "A meerkat and a warthog teach a problem free philosophy.",
    "It opens with every animal gathering at Pride Rock.",
    "Simba must avenge Mufasa and take his place as king." ]},
  { category: "Music", answer: "Adele", accept: ["adele", "adele adkins"], clues: [
    "Names albums after the age she was when writing them.",
    "Her voice once required throat surgery to save.",
    "Swept six Grammys in one night in 2012.",
    "Famous for flipping the bird at the Brits when her speech got cut.",
    "Hello from the other side." ]},
  { category: "TV Show", answer: "Seinfeld", accept: ["seinfeld"], clues: [
    "Famously described as a show about nothing.",
    "Its finale put the main characters on trial for doing nothing.",
    "Gave us close talkers, double dipping, and regifting.",
    "A comedian, his ex, his neighbor, and George navigate Manhattan.",
    "No soup for you!" ]},
  { category: "Celebrity", answer: "Kim Kardashian", accept: ["kim kardashian", "kim k", "kim kardashian west"], clues: [
    "Started as a closet organizer for celebrities like Paris Hilton.",
    "A family reality show ran for 20 seasons and spawned an empire.",
    "Broke the internet with a champagne glass magazine cover.",
    "Studying to become a lawyer like her famous father.",
    "Married Kanye, built SKIMS, mothers North, Saint, Chicago, and Psalm." ]},
  { category: "Movie", answer: "Forrest Gump", accept: ["forrest gump"], clues: [
    "This 1994 film inserts its hero into decades of real historical footage.",
    "Its hero ran across America multiple times for no particular reason.",
    "A box of chocolates explains everything about life.",
    "Tom Hanks won his second straight Oscar for this role.",
    "Run, Forrest, run!" ]},
  { category: "Music", answer: "Rihanna", accept: ["rihanna", "robyn fenty", "riri"], clues: [
    "Born in Barbados and discovered as a teenager.",
    "Built a billion dollar beauty empire called Fenty.",
    "Fans begged for a new album for nearly a decade.",
    "Performed the Super Bowl halftime show while pregnant.",
    "You can stand under her umbrella, ella, ella." ]},
  { category: "TV Show", answer: "Squid Game", accept: ["squid game"], clues: [
    "Became Netflix's most watched series ever within weeks.",
    "Contestants wear numbered green tracksuits.",
    "Childhood playground games turn deadly for cash prizes.",
    "A giant doll sings during Red Light, Green Light.",
    "456 desperate players, one massive piggy bank of money." ]},
  { category: "Celebrity", answer: "LeBron James", accept: ["lebron james", "lebron", "king james"], clues: [
    "Was on the cover of Sports Illustrated while still in high school.",
    "Announced a famous Decision on live television in 2010.",
    "Has won championships with three different franchises.",
    "Passed Kareem to become the NBA's all time leading scorer.",
    "The King, the Chosen One, from Akron, Ohio." ]},
  { category: "Movie", answer: "Home Alone", accept: ["home alone"], clues: [
    "This 1990 film is a Christmas rewatch ritual in millions of homes.",
    "Its young star became the highest paid child actor of his time.",
    "Two burglars suffer increasingly painful booby traps.",
    "A family flies to Paris and forgets something important.",
    "Kevin McCallister slaps aftershave on his cheeks and screams." ]},
  { category: "Music", answer: "Bruno Mars", accept: ["bruno mars", "peter hernandez"], clues: [
    "Performed as a tiny Elvis impersonator as a kid in Hawaii.",
    "Has headlined the Super Bowl halftime show multiple times.",
    "Formed a retro funk duo called Silk Sonic.",
    "Don't believe him? Just watch.",
    "Uptown Funk gonna give it to you." ]},
  { category: "TV Show", answer: "SpongeBob SquarePants", accept: ["spongebob squarepants", "spongebob"], clues: [
    "Created by a marine biology teacher turned animator.",
    "Its theme song starts with a pirate asking are you ready, kids.",
    "A grumpy neighbor plays clarinet badly next door.",
    "The hero flips Krabby Patties and lives in a pineapple.",
    "Who lives in a pineapple under the sea?" ]},
  { category: "Celebrity", answer: "Michael Jordan", accept: ["michael jordan", "air jordan"], clues: [
    "Was famously cut from his high school varsity team as a sophomore.",
    "Retired at his peak to play minor league baseball.",
    "His sneaker line outsells every active athlete's combined.",
    "Won six championships in six tries with one franchise.",
    "His Airness, number 23 for the Chicago Bulls." ]},
  { category: "Movie", answer: "The Avengers", accept: ["the avengers", "avengers"], clues: [
    "This 2012 film paid off four years of post credits scenes.",
    "Its heroes memorably share shawarma after the final battle.",
    "A god, a soldier, a genius, and a giant green problem team up.",
    "Loki tries to conquer Earth through a portal over New York.",
    "Earth's Mightiest Heroes assemble for the first time." ]},
  { category: "Music", answer: "Eminem", accept: ["eminem", "marshall mathers", "slim shady"], clues: [
    "Rose from Detroit rap battles to global superstardom.",
    "An 8 Mile movie dramatized his early life.",
    "Famous for an alter ego in a white tank top who stands up.",
    "Mom's spaghetti is forever linked to his most famous song.",
    "The real Slim Shady, lose yourself in the music." ]},
  { category: "TV Show", answer: "The Fresh Prince of Bel-Air", accept: ["the fresh prince of bel air", "fresh prince of bel air", "fresh prince"], clues: [
    "This 90s sitcom's theme song is recited word for word at parties.",
    "A butler named Geoffrey delivers the driest burns on TV.",
    "Carlton's dance to Tom Jones became a cultural phenomenon.",
    "In west Philadelphia, born and raised.",
    "Will moves in with his auntie and uncle in a California mansion." ]},
  { category: "Celebrity", answer: "Lady Gaga", accept: ["lady gaga", "stefani germanotta"], clues: [
    "Wore a dress made of raw meat to an awards show.",
    "Arrived at the 2011 Grammys inside a giant egg.",
    "Won an Oscar for a song from A Star Is Born.",
    "Her fans are known as Little Monsters.",
    "Born this way, with a poker face." ]},
];
